# The PublicBodyCategories structure works like this:
# [
#   "Main category name",
#       [ "tag_to_use_as_category", "Sub category title", "sentence that can describes things in this subcategory" ],
#       [ "another_tag", "Second sub category title", "another descriptive sentence for things in this subcategory"],
#   "Another main category name",
#       [ "another_tag_2", "Another sub category title", "another descriptive sentence"]
# ])


PublicBodyCategories.add(:en, [
        "Miscellaneous",
            [ "other", "Miscellaneous", "miscellaneous" ],
        _("Central government"),
            [ "department", "Ministerial departments", "a ministerial department" ],
            [ "non_ministerial_department", "Non-ministerial departments", "a non-ministerial department" ],
            [ "executive_agency", "Executive agencies", "an executive agency" ],
            [ "advisory_committee", "Advisory bodies", "an advisory body" ],
            [ "endpb", "Executive non-departmental public bodies", "an executive non-departmental public body" ],
            [ "other_cg", "Other central government bodies", "a central government body" ],
            [ "inspectorate", "Inspectorates", "an inspectorate" ],
            [ "regulator", "Regulators", "a regulator" ],
            [ "public_corporation", "Public corporations", "a public corporation" ],
        _("Local and regional"),
            [ "local_council", "Local councils", "a local council" ],
            [ "parish_council", "Town and Parish councils", "a town or parish council" ],
            [ "almo", "Housing ALMOs", "a housing ALMO" ],
            [ "assessor", "Assessors for Valuation joint boards (Scotland)", "an assessor for a valuation joint board" ],
            [ "housing_association", "Housing associations", "a housing association" ],
            [ "joint_committee", "Joint Committees", "a joint committee" ],
            [ "licensing_board", "Licensing boards (Scotland)", "a licensing board" ],
            [ "lscb", "Local safeguarding children boards", "a local safeguarding children board" ],
            [ "municipal_bank", "Municipal banks", "a municipal bank" ],
            [ "newdeal", "New Deal for Communities partnership", "a New Deal for Communities partnership" ],
            [ "nsbody", "North/south bodies", "a north/south body" ],
            [ "udc", "Urban Development Company", "an urban development company" ],
            [ "vjb", "Valuation joint boards (Scotland)", "a valuation joint board" ],
            [ "companies_owned_by_local_gov", "Companies owned by local government", "a company owned by local government" ],
            [ "bodies_funded_by_local_gov", "Bodies funded by local government", "a body funded by local government" ],
        "Education",
            [ "university", "Universities", "a university" ],
            [ "university_college", "University colleges", "a university college" ],
            [ "cambridge_college", "Cambridge colleges", "a Cambridge college" ],
            [ "durham_college", "Durham colleges", "a Durham college" ],
            [ "oxford_college", "Oxford colleges", "an Oxford college or permanent private hall" ],
            [ "group_of_universities", "Groups of universities", "a group of universities" ],
            [ "university_owned_company", "University owned companies", "a university owned company" ],
            [ "hei", "Higher education institutions", "a higher educational institution" ],
            [ "fei", "Further education institutions", "a further educational institution" ],
            [ "academies", "Academies", "an academy" ],
            [ "school", "Schools", "a school" ],
            [ "exam_board", "Exam boards", "an exam board" ],
            [ "research_council", "Research councils", "a research council" ],
            [ "lib_board", "Education and library boards", "an education and library board" ],
            [ "rbc", "Regional Broadband Consortia", "a regional broadband consortium" ],
            [ "school_inspectorate", "School inspectorates", "a school inspectorate" ],
        "Environment and agriculture",
            [ "adhac", "Agricultural dwelling house advisory committees", "an agriculatural dwelling house advisory committee" ],
            [ "awc", "Agricultural wages committees", "an agriculatural wages committee" ],
            [ "ifca", "Inshore fisheries and conservation authorities", "an inshore fisheries and conservation authority" ],
            [ "idb", "Internal drainage boards", "an internal drainage board" ],
            [ "mcz", "Marine conservation zones", "a marine conservation zone" ],
            [ "npa", "National park authorities", "a national park authority" ],
            [ "rpa", "Regional park authorities", "a regional park authority" ],
            [ "sea_fishery_committee", "Sea fisheries committees", "a sea fisheries committee" ],
            [ "wda", "Waste disposal authorities", "a waste disposal authority" ],
            [ "wma", "Waste management authorities (Northern Ireland)", "a waste management authority" ],
            [ "watercompanies", "Water companies", "a water company" ],
            [ "zoo", "Zoos", "a zoo" ],
        "Health",
            [ "nhs", "NHS bodies", "a part of the National Health Service" ],
            [ "nhstrust", "NHS trusts", "an NHS trust" ],
            [ "pct", "Primary care trusts", "a primary care trust" ],
            [ "nhswales", "NHS in Wales", "a part of the NHS in Wales" ],
            [ "chc", "Community Health Councils (Wales)", "an independent local NHS watchdog in Wales" ],
            [ "nhsni", "NHS in Northern Ireland", "part of the NHS in Northern Ireland" ],
            [ "commissioning_consortium", "GP commissioning consortia", "a GP commissioning consortium" ],
            [ "hscr", "Health / social care", "Relating to health / social care" ],
            [ "his", "Health Informatic Services", "a health informatics service" ],
            [ "optician", "Opticians", "an optician"],
            [ "pharmacy", "Pharmacies", "a pharmacy"],
            [ "pha", "Port health authorities", "a port health authority"],
            [ "pho", "Public health observatories", "a public health observatory"],
            [ "sha", "Strategic health authorities", "a strategic health authority" ],
            [ "specialha", "Special health authorities", "a special health authority" ],
        "Media and culture",
            [ "media", "Media", "a media organisation" ],
            [ "museum", "Museums and galleries", "a museum or gallery" ],
        "Military and security services",
            [ "armed_forces", "Armed Forces", "part of the Armed Forces of the Crown" ],
            [ "military_college", "Military colleges", "a military college" ],
            [ "security_services", "Security services", "a security services body" ],
        "Emergency services",
            [ "police", "Policing bodies", "a policing body" ],
            [ "police_force", "Police forces", "a police force" ],
            [ "police_crime_commissioner", "Police and Crime Commissioners", "an office of a Police and Crime Commissioner" ],
            [ "police_crime_panel", "Police and Crime Panels", "a Police and Crime Panel" ],
            [ "dpp", "District policing partnerships", "a district policing partnership" ],
            [ "fire_service", "Fire and rescue services", "a fire and rescue service" ],
        "Law making bodies, the courts and the legal system",
            [ "ukparliament", "UK Parliament", "part of the UK Parliament"],
            [ "national_parliament_or_assembly", "National Parliaments and Assemblies", "a national parliament or assembly"],
            [ "court", "Courts", "a court"],
            [ "coroners_office", "Coroners' offices", "an office of a coroner"],
            [ "tribunal", "Tribunals", "a tribunal"],
            [ "approved_regulator", "Approved regulators of legal services", "an approved regulator of legal services"],
            [ "cja", "Community justice authorities", "a criminal justice authority" ],
            [ "imb", "Independent monitoring boards (for prisons)", "an independent monitoring board" ],
            [ "prob_board", "Probation boards", "a probation board" ],
            [ "probation_trust", "Probation trusts", "a probation board" ],
            [ "rules_committee", "Rules committees", "a rules committee" ],
        "Transport",
            [ "airport", "Airport companies", "an airport company" ],
            [ "bus_company", "Bus companies", "a bus company" ],
            [ "navigation_authority", "Navigation authorities", "a navigation authority" ],
            [ "npte", "Passenger transport executives", "a passenger transport executive" ],
            [ "port_authority", "Port authorities", "a port authority" ],
            [ "srp", "Safer Roads Partnership", "a safer roads partnership" ],
            [ "toll_company", "Toll companies", "a toll company" ],
            [ "trunk_road_agency", "Trunk road agencies (Wales)", "a trunk road agency" ],
        "Groups of public authorities",
            [ "association", "Associations of public authorities", "an association of public authorities"],
            [ "group_of_universities", "Groups of universities", "a group of universities" ],
            [ "pbo", "Professional buying organisations", "a professional buying organisation"],
        "Other",
            [ "charter_trustees", "Charter trustees", "a group of charter trustees"],
            [ "public_infrastructure", "Companies controlling national infrastructure", "a company controlling national infrastructure"],
            [ "inns_of_court", "Inns of court", "an Inn of Court" ],
            [ "ombudsman", "Ombudsmen", "an ombudsman" ],
            [ "professional_body", "Professional bodies", "a professional body" ],
            [ "publicly_funded_charities", "Publicly funded charities", "a publicly funded charity" ],
            [ "duchy", "Royal duchies", "a Royal Duchy" ],
        "Defunct bodies",
          [ "defunct", "Defunct bodies", "a body that is now defunct" ],
          [ "rcc", "Cultural consortia", "a cultural consortium" ],
          [ "government_office", "Government offices for the regions", "a government office for the regions" ],
          [ "police_authority", "Police authorities", "a police authority" ],
          [ "regional_assembly", "Regional assemblies", "a regional assembly" ],
          [ "rda", "Regional development agencies", "a regional development agency" ],
          [ "rfdc", "Regional flood defence committees", "a regional flood defence committee" ]
    ]
)
