name: CI

on:
  push:
    branches: [master, develop]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / PostgreSQL ${{ matrix.postgres }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
        - { ruby: '3.2', postgres: 13.5 }

    services:
      postgres:
        image: fixmystreet/postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/alaveteli_test
      RAILS_ENV: test

    steps:
    - name: Checkout Alaveteli
      uses: actions/checkout@v2
      with:
        repository: mysociety/alaveteli
        ref: develop
        path: core
        submodules: true
        fetch-depth: 0

    - name: Create Alaveteli theme directory
      run: |
        mkdir alaveteli-themes

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: alaveteli-themes/whatdotheyknow-theme

    - name: Install packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y update
        sudo apt-get -y install exim4-daemon-light
        sudo apt-get -y install `cut -d " " -f 1 config/packages.ubuntu-focal | egrep -v "(^#|wkhtml|bundler|^ruby|^rake)"`
      working-directory: core

    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: core

    - name: Setup database
      run: |
        psql postgres://postgres:postgres@localhost:5432 <<-EOSQL
          CREATE DATABASE template_utf8 TEMPLATE template0 ENCODING "UTF-8";
          UPDATE pg_database SET datistemplate=true WHERE datname='template_utf8';
          CREATE DATABASE alaveteli_test TEMPLATE template_utf8;
        EOSQL
      working-directory: core

    - name: Configure application and storage
      run: |
        cp config/general.yml-example config/general-whatdotheyknow-theme.yml
        cp config/storage.yml-example config/storage.yml
      working-directory: core

    - name: Install theme
      run: |
        script/switch-theme.rb whatdotheyknow-theme
        bundle exec rake themes:install
      working-directory: core

    - name: Migrate database
      run: |
        bundle exec rails db:migrate
      working-directory: core

    - name: Run tests
      run: |
        bundle exec rspec --format Fivemat lib/themes/whatdotheyknow-theme/spec
      working-directory: core
